version: '2'
 
services:
 nginx:
   image: csc_dtrace_nginx:1.0
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   depends_on:
     - calculator

 calculator:
   image: calculator:1.0
   restart: always
   build: ./service/calculator
   environment:
     - LISTEN_PORT=5000
     - SRV_PARSER=parser
     - SRV_PRESENTER=presenter
   command: gunicorn -w 2 -b :5000 --log-level info --access-logfile '-' --error-logfile '-' main:app
   depends_on:
     - parser
     - presenter

 parser:
   image: parser:1.0
   restart: always
   build: ./service/parser
   environment:
     - LISTEN_PORT=5001
   command: gunicorn -w 2 -b :5001 --log-level info --access-logfile '-' --error-logfile '-' main:app

 presenter:
   image: presenter:1.0
   restart: always
   build: ./service/presenter
   environment:
     - LISTEN_PORT=5002
   command: gunicorn -w 2 -b :5002 --log-level info --access-logfile '-' --error-logfile '-' main:app