version: '2'

services:
    nginx:
        image: nginx:1.17.10-alpine
        restart: always
        volumes:
            - ${PWD}/test-app/service/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${PWD}/test-app/service/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - calculator
            - logspout

    calculator:
        image: calculator:1.0
        restart: always
        build: ./test-app/service/calculator
        environment:
            - LISTEN_PORT=5000
            - SRV_PARSER=parser
            - SRV_PRESENTER=presenter
        command: gunicorn -b :5000 --config /etc/gunicorn/config.py main:app
        depends_on:
            - parser
            - presenter
            - logspout

    parser:
        image: parser:1.0
        restart: always
        build: ./test-app/service/parser
        environment:
            - LISTEN_PORT=5001
        command: gunicorn -w 2 -b :5001 --config /etc/gunicorn/config.py main:app
        depends_on:
            - logspout

    presenter:
        image: presenter:1.0
        restart: always
        build: ./test-app/service/presenter
        environment:
            - LISTEN_PORT=5002
        command: gunicorn -w 2 -b :5002 --config /etc/gunicorn/config.py main:app
        depends_on:
            - logspout

    logspout:
        image: gliderlabs/logspout:v3.2.11
        ports:
            - "1080:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock

