FROM python:3.6.10-alpine3.11
COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt
RUN rm /tmp/requirements.txt
COPY config.py /etc/gunicorn/config.py
COPY csc_dtrace_glogger.py /usr/local/lib/python3.6/site-packages/csc_dtrace_glogger.py